/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonSize, ControlType as ControlType1, GenericStatus, HeaderControlType, IBoolFunction, IUIEventHandler, LabelOrientation, PageKey } from "./global/Types";
import { ControlType } from "./components/components/input-control/InputControlTypes";
import { IChangeHandler, IControlListOption, IKeyPressHandler } from "./components/components/labeled-control/Common";
import { ISearchCallback } from "./components/components/search-panel/Common";
export { ButtonSize, ControlType as ControlType1, GenericStatus, HeaderControlType, IBoolFunction, IUIEventHandler, LabelOrientation, PageKey } from "./global/Types";
export { ControlType } from "./components/components/input-control/InputControlTypes";
export { IChangeHandler, IControlListOption, IKeyPressHandler } from "./components/components/labeled-control/Common";
export { ISearchCallback } from "./components/components/search-panel/Common";
export namespace Components {
    interface AdminCreatePersonPage {
    }
    interface AdminHomePage {
    }
    interface AdminSideMenu {
        /**
          * @default false
         */
        "isOpen": boolean;
    }
    interface AnnotateHostPage {
    }
    interface AppRoot {
    }
    interface AuthorizedHeader {
        /**
          * @default null
         */
        "canGoBack": IBoolFunction;
        "controlType": HeaderControlType;
        /**
          * @default null
         */
        "pageTitle": string;
        /**
          * @default false
         */
        "useDefault": boolean;
    }
    interface BvbrcButton {
        /**
          * @default null
         */
        "buttonKey": string;
        /**
          * @default null
         */
        "clickHandler": IUIEventHandler;
        /**
          * @default null
         */
        "icon": string;
        /**
          * @default false
         */
        "iconOnRight": boolean;
        /**
          * @default false
         */
        "isDisabled": boolean;
        /**
          * @default false
         */
        "isLoading": boolean;
        "label": string;
        /**
          * @default CustomIcon.spinner
         */
        "loadingIcon": string;
        /**
          * @default "Loading"
         */
        "loadingLabel": string;
        "refresh": () => Promise<void>;
        /**
          * @default ButtonSize.medium
         */
        "size": ButtonSize;
        /**
          * @default null
         */
        "status": GenericStatus;
    }
    interface BvbrcDialog {
        "cancelIcon": string;
        /**
          * @default "Cancel"
         */
        "cancelLabel": string;
        "close": () => Promise<void>;
        "open": () => Promise<void>;
    }
    interface BvbrcIonButton {
    }
    interface CuratedWordsPage {
    }
    interface CurationTabs {
    }
    interface CuratorSideMenu {
        /**
          * @default false
         */
        "isOpen": boolean;
    }
    interface HomePage {
    }
    interface HostTaxaMatchesPage {
    }
    interface HostsPage {
    }
    interface InputControl {
        "controlType": ControlType;
        "cssClassNames": string[];
        "isReadOnly": boolean;
        "labelText": string;
        "value": string;
    }
    interface LabeledControl {
        /**
          * @default null
         */
        "attributeKey": string;
        /**
          * @default null
         */
        "changeHandler": IChangeHandler;
        "clearValue": () => Promise<void>;
        /**
          * @default ControlType.text
         */
        "controlType": ControlType1;
        "getValue": () => Promise<string>;
        /**
          * @default null
         */
        "initialValue": any;
        /**
          * @default false
         */
        "isDisabled": boolean;
        /**
          * @default false
         */
        "isReadOnly": boolean;
        /**
          * @default false
         */
        "isRequired": boolean;
        /**
          * @default null
         */
        "keypressHandler": IKeyPressHandler;
        /**
          * @default null
         */
        "keyupHandler": IChangeHandler;
        /**
          * @default LabelOrientation.left
         */
        "labelOrientation": LabelOrientation;
        /**
          * @default null
         */
        "labelText": string;
        "listOptions": IControlListOption[];
        /**
          * @default false
         */
        "spellcheck": boolean;
        /**
          * @default GenericStatus.unspecified
         */
        "status": GenericStatus;
        /**
          * @default null
         */
        "statusMessage": string;
        /**
          * @default 3
         */
        "textAreaRows": number;
        /**
          * @default null
         */
        "textPlaceholder": string;
    }
    interface LoginPage {
    }
    interface LookupHostPage {
    }
    interface ResetPasswordPage {
    }
    interface SearchPanel {
        /**
          * @default null
         */
        "pageKey": PageKey;
        /**
          * @default "Enter search text (optional)"
         */
        "placeholderText": string;
        /**
          * @default null
         */
        "searchCallback": ISearchCallback;
        /**
          * @default true
         */
        "useState": boolean;
    }
    interface SideMenuEntry {
        "icon": string;
        "label": string;
    }
    interface TaxonomySearchPage {
    }
    interface UserProfilePage {
    }
    interface ViewHostPage {
    }
}
declare global {
    interface HTMLAdminCreatePersonPageElement extends Components.AdminCreatePersonPage, HTMLStencilElement {
    }
    var HTMLAdminCreatePersonPageElement: {
        prototype: HTMLAdminCreatePersonPageElement;
        new (): HTMLAdminCreatePersonPageElement;
    };
    interface HTMLAdminHomePageElement extends Components.AdminHomePage, HTMLStencilElement {
    }
    var HTMLAdminHomePageElement: {
        prototype: HTMLAdminHomePageElement;
        new (): HTMLAdminHomePageElement;
    };
    interface HTMLAdminSideMenuElement extends Components.AdminSideMenu, HTMLStencilElement {
    }
    var HTMLAdminSideMenuElement: {
        prototype: HTMLAdminSideMenuElement;
        new (): HTMLAdminSideMenuElement;
    };
    interface HTMLAnnotateHostPageElement extends Components.AnnotateHostPage, HTMLStencilElement {
    }
    var HTMLAnnotateHostPageElement: {
        prototype: HTMLAnnotateHostPageElement;
        new (): HTMLAnnotateHostPageElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAuthorizedHeaderElement extends Components.AuthorizedHeader, HTMLStencilElement {
    }
    var HTMLAuthorizedHeaderElement: {
        prototype: HTMLAuthorizedHeaderElement;
        new (): HTMLAuthorizedHeaderElement;
    };
    interface HTMLBvbrcButtonElement extends Components.BvbrcButton, HTMLStencilElement {
    }
    var HTMLBvbrcButtonElement: {
        prototype: HTMLBvbrcButtonElement;
        new (): HTMLBvbrcButtonElement;
    };
    interface HTMLBvbrcDialogElement extends Components.BvbrcDialog, HTMLStencilElement {
    }
    var HTMLBvbrcDialogElement: {
        prototype: HTMLBvbrcDialogElement;
        new (): HTMLBvbrcDialogElement;
    };
    interface HTMLBvbrcIonButtonElement extends Components.BvbrcIonButton, HTMLStencilElement {
    }
    var HTMLBvbrcIonButtonElement: {
        prototype: HTMLBvbrcIonButtonElement;
        new (): HTMLBvbrcIonButtonElement;
    };
    interface HTMLCuratedWordsPageElement extends Components.CuratedWordsPage, HTMLStencilElement {
    }
    var HTMLCuratedWordsPageElement: {
        prototype: HTMLCuratedWordsPageElement;
        new (): HTMLCuratedWordsPageElement;
    };
    interface HTMLCurationTabsElement extends Components.CurationTabs, HTMLStencilElement {
    }
    var HTMLCurationTabsElement: {
        prototype: HTMLCurationTabsElement;
        new (): HTMLCurationTabsElement;
    };
    interface HTMLCuratorSideMenuElement extends Components.CuratorSideMenu, HTMLStencilElement {
    }
    var HTMLCuratorSideMenuElement: {
        prototype: HTMLCuratorSideMenuElement;
        new (): HTMLCuratorSideMenuElement;
    };
    interface HTMLHomePageElement extends Components.HomePage, HTMLStencilElement {
    }
    var HTMLHomePageElement: {
        prototype: HTMLHomePageElement;
        new (): HTMLHomePageElement;
    };
    interface HTMLHostTaxaMatchesPageElement extends Components.HostTaxaMatchesPage, HTMLStencilElement {
    }
    var HTMLHostTaxaMatchesPageElement: {
        prototype: HTMLHostTaxaMatchesPageElement;
        new (): HTMLHostTaxaMatchesPageElement;
    };
    interface HTMLHostsPageElement extends Components.HostsPage, HTMLStencilElement {
    }
    var HTMLHostsPageElement: {
        prototype: HTMLHostsPageElement;
        new (): HTMLHostsPageElement;
    };
    interface HTMLInputControlElement extends Components.InputControl, HTMLStencilElement {
    }
    var HTMLInputControlElement: {
        prototype: HTMLInputControlElement;
        new (): HTMLInputControlElement;
    };
    interface HTMLLabeledControlElement extends Components.LabeledControl, HTMLStencilElement {
    }
    var HTMLLabeledControlElement: {
        prototype: HTMLLabeledControlElement;
        new (): HTMLLabeledControlElement;
    };
    interface HTMLLoginPageElement extends Components.LoginPage, HTMLStencilElement {
    }
    var HTMLLoginPageElement: {
        prototype: HTMLLoginPageElement;
        new (): HTMLLoginPageElement;
    };
    interface HTMLLookupHostPageElement extends Components.LookupHostPage, HTMLStencilElement {
    }
    var HTMLLookupHostPageElement: {
        prototype: HTMLLookupHostPageElement;
        new (): HTMLLookupHostPageElement;
    };
    interface HTMLResetPasswordPageElement extends Components.ResetPasswordPage, HTMLStencilElement {
    }
    var HTMLResetPasswordPageElement: {
        prototype: HTMLResetPasswordPageElement;
        new (): HTMLResetPasswordPageElement;
    };
    interface HTMLSearchPanelElement extends Components.SearchPanel, HTMLStencilElement {
    }
    var HTMLSearchPanelElement: {
        prototype: HTMLSearchPanelElement;
        new (): HTMLSearchPanelElement;
    };
    interface HTMLSideMenuEntryElement extends Components.SideMenuEntry, HTMLStencilElement {
    }
    var HTMLSideMenuEntryElement: {
        prototype: HTMLSideMenuEntryElement;
        new (): HTMLSideMenuEntryElement;
    };
    interface HTMLTaxonomySearchPageElement extends Components.TaxonomySearchPage, HTMLStencilElement {
    }
    var HTMLTaxonomySearchPageElement: {
        prototype: HTMLTaxonomySearchPageElement;
        new (): HTMLTaxonomySearchPageElement;
    };
    interface HTMLUserProfilePageElement extends Components.UserProfilePage, HTMLStencilElement {
    }
    var HTMLUserProfilePageElement: {
        prototype: HTMLUserProfilePageElement;
        new (): HTMLUserProfilePageElement;
    };
    interface HTMLViewHostPageElement extends Components.ViewHostPage, HTMLStencilElement {
    }
    var HTMLViewHostPageElement: {
        prototype: HTMLViewHostPageElement;
        new (): HTMLViewHostPageElement;
    };
    interface HTMLElementTagNameMap {
        "admin-create-person-page": HTMLAdminCreatePersonPageElement;
        "admin-home-page": HTMLAdminHomePageElement;
        "admin-side-menu": HTMLAdminSideMenuElement;
        "annotate-host-page": HTMLAnnotateHostPageElement;
        "app-root": HTMLAppRootElement;
        "authorized-header": HTMLAuthorizedHeaderElement;
        "bvbrc-button": HTMLBvbrcButtonElement;
        "bvbrc-dialog": HTMLBvbrcDialogElement;
        "bvbrc-ion-button": HTMLBvbrcIonButtonElement;
        "curated-words-page": HTMLCuratedWordsPageElement;
        "curation-tabs": HTMLCurationTabsElement;
        "curator-side-menu": HTMLCuratorSideMenuElement;
        "home-page": HTMLHomePageElement;
        "host-taxa-matches-page": HTMLHostTaxaMatchesPageElement;
        "hosts-page": HTMLHostsPageElement;
        "input-control": HTMLInputControlElement;
        "labeled-control": HTMLLabeledControlElement;
        "login-page": HTMLLoginPageElement;
        "lookup-host-page": HTMLLookupHostPageElement;
        "reset-password-page": HTMLResetPasswordPageElement;
        "search-panel": HTMLSearchPanelElement;
        "side-menu-entry": HTMLSideMenuEntryElement;
        "taxonomy-search-page": HTMLTaxonomySearchPageElement;
        "user-profile-page": HTMLUserProfilePageElement;
        "view-host-page": HTMLViewHostPageElement;
    }
}
declare namespace LocalJSX {
    interface AdminCreatePersonPage {
    }
    interface AdminHomePage {
    }
    interface AdminSideMenu {
        /**
          * @default false
         */
        "isOpen"?: boolean;
    }
    interface AnnotateHostPage {
    }
    interface AppRoot {
    }
    interface AuthorizedHeader {
        /**
          * @default null
         */
        "canGoBack"?: IBoolFunction;
        "controlType"?: HeaderControlType;
        /**
          * @default null
         */
        "pageTitle"?: string;
        /**
          * @default false
         */
        "useDefault"?: boolean;
    }
    interface BvbrcButton {
        /**
          * @default null
         */
        "buttonKey"?: string;
        /**
          * @default null
         */
        "clickHandler"?: IUIEventHandler;
        /**
          * @default null
         */
        "icon"?: string;
        /**
          * @default false
         */
        "iconOnRight"?: boolean;
        /**
          * @default false
         */
        "isDisabled"?: boolean;
        /**
          * @default false
         */
        "isLoading"?: boolean;
        "label"?: string;
        /**
          * @default CustomIcon.spinner
         */
        "loadingIcon"?: string;
        /**
          * @default "Loading"
         */
        "loadingLabel"?: string;
        /**
          * @default ButtonSize.medium
         */
        "size"?: ButtonSize;
        /**
          * @default null
         */
        "status"?: GenericStatus;
    }
    interface BvbrcDialog {
        "cancelIcon"?: string;
        /**
          * @default "Cancel"
         */
        "cancelLabel"?: string;
    }
    interface BvbrcIonButton {
    }
    interface CuratedWordsPage {
    }
    interface CurationTabs {
    }
    interface CuratorSideMenu {
        /**
          * @default false
         */
        "isOpen"?: boolean;
    }
    interface HomePage {
    }
    interface HostTaxaMatchesPage {
    }
    interface HostsPage {
    }
    interface InputControl {
        "controlType"?: ControlType;
        "cssClassNames"?: string[];
        "isReadOnly"?: boolean;
        "labelText"?: string;
        "value"?: string;
    }
    interface LabeledControl {
        /**
          * @default null
         */
        "attributeKey"?: string;
        /**
          * @default null
         */
        "changeHandler"?: IChangeHandler;
        /**
          * @default ControlType.text
         */
        "controlType"?: ControlType1;
        /**
          * @default null
         */
        "initialValue"?: any;
        /**
          * @default false
         */
        "isDisabled"?: boolean;
        /**
          * @default false
         */
        "isReadOnly"?: boolean;
        /**
          * @default false
         */
        "isRequired"?: boolean;
        /**
          * @default null
         */
        "keypressHandler"?: IKeyPressHandler;
        /**
          * @default null
         */
        "keyupHandler"?: IChangeHandler;
        /**
          * @default LabelOrientation.left
         */
        "labelOrientation"?: LabelOrientation;
        /**
          * @default null
         */
        "labelText"?: string;
        "listOptions"?: IControlListOption[];
        /**
          * @default false
         */
        "spellcheck"?: boolean;
        /**
          * @default GenericStatus.unspecified
         */
        "status"?: GenericStatus;
        /**
          * @default null
         */
        "statusMessage"?: string;
        /**
          * @default 3
         */
        "textAreaRows"?: number;
        /**
          * @default null
         */
        "textPlaceholder"?: string;
    }
    interface LoginPage {
    }
    interface LookupHostPage {
    }
    interface ResetPasswordPage {
    }
    interface SearchPanel {
        /**
          * @default null
         */
        "pageKey"?: PageKey;
        /**
          * @default "Enter search text (optional)"
         */
        "placeholderText"?: string;
        /**
          * @default null
         */
        "searchCallback"?: ISearchCallback;
        /**
          * @default true
         */
        "useState"?: boolean;
    }
    interface SideMenuEntry {
        "icon"?: string;
        "label"?: string;
    }
    interface TaxonomySearchPage {
    }
    interface UserProfilePage {
    }
    interface ViewHostPage {
    }

    interface AdminSideMenuAttributes {
        "isOpen": boolean;
    }
    interface AuthorizedHeaderAttributes {
        "controlType": HeaderControlType;
        "pageTitle": string;
        "useDefault": boolean;
    }
    interface BvbrcButtonAttributes {
        "buttonKey": string;
        "icon": string;
        "iconOnRight": boolean;
        "isDisabled": boolean;
        "isLoading": boolean;
        "label": string;
        "loadingIcon": string;
        "loadingLabel": string;
        "size": ButtonSize;
        "status": GenericStatus;
    }
    interface BvbrcDialogAttributes {
        "cancelIcon": string;
        "cancelLabel": string;
    }
    interface CuratorSideMenuAttributes {
        "isOpen": boolean;
    }
    interface InputControlAttributes {
        "controlType": ControlType;
        "isReadOnly": boolean;
        "labelText": string;
        "value": string;
    }
    interface LabeledControlAttributes {
        "attributeKey": string;
        "controlType": ControlType;
        "initialValue": string;
        "isDisabled": boolean;
        "isReadOnly": boolean;
        "isRequired": boolean;
        "labelOrientation": LabelOrientation;
        "labelText": string;
        "spellcheck": boolean;
        "status": GenericStatus;
        "statusMessage": string;
        "textAreaRows": number;
        "textPlaceholder": string;
    }
    interface SearchPanelAttributes {
        "pageKey": PageKey;
        "placeholderText": string;
        "useState": boolean;
    }
    interface SideMenuEntryAttributes {
        "icon": string;
        "label": string;
    }

    interface IntrinsicElements {
        "admin-create-person-page": AdminCreatePersonPage;
        "admin-home-page": AdminHomePage;
        "admin-side-menu": Omit<AdminSideMenu, keyof AdminSideMenuAttributes> & { [K in keyof AdminSideMenu & keyof AdminSideMenuAttributes]?: AdminSideMenu[K] } & { [K in keyof AdminSideMenu & keyof AdminSideMenuAttributes as `attr:${K}`]?: AdminSideMenuAttributes[K] } & { [K in keyof AdminSideMenu & keyof AdminSideMenuAttributes as `prop:${K}`]?: AdminSideMenu[K] };
        "annotate-host-page": AnnotateHostPage;
        "app-root": AppRoot;
        "authorized-header": Omit<AuthorizedHeader, keyof AuthorizedHeaderAttributes> & { [K in keyof AuthorizedHeader & keyof AuthorizedHeaderAttributes]?: AuthorizedHeader[K] } & { [K in keyof AuthorizedHeader & keyof AuthorizedHeaderAttributes as `attr:${K}`]?: AuthorizedHeaderAttributes[K] } & { [K in keyof AuthorizedHeader & keyof AuthorizedHeaderAttributes as `prop:${K}`]?: AuthorizedHeader[K] };
        "bvbrc-button": Omit<BvbrcButton, keyof BvbrcButtonAttributes> & { [K in keyof BvbrcButton & keyof BvbrcButtonAttributes]?: BvbrcButton[K] } & { [K in keyof BvbrcButton & keyof BvbrcButtonAttributes as `attr:${K}`]?: BvbrcButtonAttributes[K] } & { [K in keyof BvbrcButton & keyof BvbrcButtonAttributes as `prop:${K}`]?: BvbrcButton[K] };
        "bvbrc-dialog": Omit<BvbrcDialog, keyof BvbrcDialogAttributes> & { [K in keyof BvbrcDialog & keyof BvbrcDialogAttributes]?: BvbrcDialog[K] } & { [K in keyof BvbrcDialog & keyof BvbrcDialogAttributes as `attr:${K}`]?: BvbrcDialogAttributes[K] } & { [K in keyof BvbrcDialog & keyof BvbrcDialogAttributes as `prop:${K}`]?: BvbrcDialog[K] };
        "bvbrc-ion-button": BvbrcIonButton;
        "curated-words-page": CuratedWordsPage;
        "curation-tabs": CurationTabs;
        "curator-side-menu": Omit<CuratorSideMenu, keyof CuratorSideMenuAttributes> & { [K in keyof CuratorSideMenu & keyof CuratorSideMenuAttributes]?: CuratorSideMenu[K] } & { [K in keyof CuratorSideMenu & keyof CuratorSideMenuAttributes as `attr:${K}`]?: CuratorSideMenuAttributes[K] } & { [K in keyof CuratorSideMenu & keyof CuratorSideMenuAttributes as `prop:${K}`]?: CuratorSideMenu[K] };
        "home-page": HomePage;
        "host-taxa-matches-page": HostTaxaMatchesPage;
        "hosts-page": HostsPage;
        "input-control": Omit<InputControl, keyof InputControlAttributes> & { [K in keyof InputControl & keyof InputControlAttributes]?: InputControl[K] } & { [K in keyof InputControl & keyof InputControlAttributes as `attr:${K}`]?: InputControlAttributes[K] } & { [K in keyof InputControl & keyof InputControlAttributes as `prop:${K}`]?: InputControl[K] };
        "labeled-control": Omit<LabeledControl, keyof LabeledControlAttributes> & { [K in keyof LabeledControl & keyof LabeledControlAttributes]?: LabeledControl[K] } & { [K in keyof LabeledControl & keyof LabeledControlAttributes as `attr:${K}`]?: LabeledControlAttributes[K] } & { [K in keyof LabeledControl & keyof LabeledControlAttributes as `prop:${K}`]?: LabeledControl[K] };
        "login-page": LoginPage;
        "lookup-host-page": LookupHostPage;
        "reset-password-page": ResetPasswordPage;
        "search-panel": Omit<SearchPanel, keyof SearchPanelAttributes> & { [K in keyof SearchPanel & keyof SearchPanelAttributes]?: SearchPanel[K] } & { [K in keyof SearchPanel & keyof SearchPanelAttributes as `attr:${K}`]?: SearchPanelAttributes[K] } & { [K in keyof SearchPanel & keyof SearchPanelAttributes as `prop:${K}`]?: SearchPanel[K] };
        "side-menu-entry": Omit<SideMenuEntry, keyof SideMenuEntryAttributes> & { [K in keyof SideMenuEntry & keyof SideMenuEntryAttributes]?: SideMenuEntry[K] } & { [K in keyof SideMenuEntry & keyof SideMenuEntryAttributes as `attr:${K}`]?: SideMenuEntryAttributes[K] } & { [K in keyof SideMenuEntry & keyof SideMenuEntryAttributes as `prop:${K}`]?: SideMenuEntry[K] };
        "taxonomy-search-page": TaxonomySearchPage;
        "user-profile-page": UserProfilePage;
        "view-host-page": ViewHostPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "admin-create-person-page": LocalJSX.IntrinsicElements["admin-create-person-page"] & JSXBase.HTMLAttributes<HTMLAdminCreatePersonPageElement>;
            "admin-home-page": LocalJSX.IntrinsicElements["admin-home-page"] & JSXBase.HTMLAttributes<HTMLAdminHomePageElement>;
            "admin-side-menu": LocalJSX.IntrinsicElements["admin-side-menu"] & JSXBase.HTMLAttributes<HTMLAdminSideMenuElement>;
            "annotate-host-page": LocalJSX.IntrinsicElements["annotate-host-page"] & JSXBase.HTMLAttributes<HTMLAnnotateHostPageElement>;
            "app-root": LocalJSX.IntrinsicElements["app-root"] & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "authorized-header": LocalJSX.IntrinsicElements["authorized-header"] & JSXBase.HTMLAttributes<HTMLAuthorizedHeaderElement>;
            "bvbrc-button": LocalJSX.IntrinsicElements["bvbrc-button"] & JSXBase.HTMLAttributes<HTMLBvbrcButtonElement>;
            "bvbrc-dialog": LocalJSX.IntrinsicElements["bvbrc-dialog"] & JSXBase.HTMLAttributes<HTMLBvbrcDialogElement>;
            "bvbrc-ion-button": LocalJSX.IntrinsicElements["bvbrc-ion-button"] & JSXBase.HTMLAttributes<HTMLBvbrcIonButtonElement>;
            "curated-words-page": LocalJSX.IntrinsicElements["curated-words-page"] & JSXBase.HTMLAttributes<HTMLCuratedWordsPageElement>;
            "curation-tabs": LocalJSX.IntrinsicElements["curation-tabs"] & JSXBase.HTMLAttributes<HTMLCurationTabsElement>;
            "curator-side-menu": LocalJSX.IntrinsicElements["curator-side-menu"] & JSXBase.HTMLAttributes<HTMLCuratorSideMenuElement>;
            "home-page": LocalJSX.IntrinsicElements["home-page"] & JSXBase.HTMLAttributes<HTMLHomePageElement>;
            "host-taxa-matches-page": LocalJSX.IntrinsicElements["host-taxa-matches-page"] & JSXBase.HTMLAttributes<HTMLHostTaxaMatchesPageElement>;
            "hosts-page": LocalJSX.IntrinsicElements["hosts-page"] & JSXBase.HTMLAttributes<HTMLHostsPageElement>;
            "input-control": LocalJSX.IntrinsicElements["input-control"] & JSXBase.HTMLAttributes<HTMLInputControlElement>;
            "labeled-control": LocalJSX.IntrinsicElements["labeled-control"] & JSXBase.HTMLAttributes<HTMLLabeledControlElement>;
            "login-page": LocalJSX.IntrinsicElements["login-page"] & JSXBase.HTMLAttributes<HTMLLoginPageElement>;
            "lookup-host-page": LocalJSX.IntrinsicElements["lookup-host-page"] & JSXBase.HTMLAttributes<HTMLLookupHostPageElement>;
            "reset-password-page": LocalJSX.IntrinsicElements["reset-password-page"] & JSXBase.HTMLAttributes<HTMLResetPasswordPageElement>;
            "search-panel": LocalJSX.IntrinsicElements["search-panel"] & JSXBase.HTMLAttributes<HTMLSearchPanelElement>;
            "side-menu-entry": LocalJSX.IntrinsicElements["side-menu-entry"] & JSXBase.HTMLAttributes<HTMLSideMenuEntryElement>;
            "taxonomy-search-page": LocalJSX.IntrinsicElements["taxonomy-search-page"] & JSXBase.HTMLAttributes<HTMLTaxonomySearchPageElement>;
            "user-profile-page": LocalJSX.IntrinsicElements["user-profile-page"] & JSXBase.HTMLAttributes<HTMLUserProfilePageElement>;
            "view-host-page": LocalJSX.IntrinsicElements["view-host-page"] & JSXBase.HTMLAttributes<HTMLViewHostPageElement>;
        }
    }
}
