--------------------------------------------------------------------------------
-- Index fragmentation report + optional rebuild (SQL Server T-SQL)
-- Run in the target database context (e.g., USE YourDatabase;)
--
-- This was generated by Duck.ai (GPT-5 mini) on 03/31/26
--------------------------------------------------------------------------------

-- Parameters: adjust if desired
DECLARE @MinPageCount INT = 100;         -- only consider indexes with at least this many pages
DECLARE @ReorgThreshold FLOAT = 5.0;    -- >= this and <= @RebuildThreshold => REORGANIZE
DECLARE @RebuildThreshold FLOAT = 30.0; -- > this => REBUILD
DECLARE @OnlineRebuild BIT = 1;         -- 1 = attempt ONLINE = ON (Enterprise/appropriate SKUs), 0 = OFF

--------------------------------------------------------------------------------
-- Fragmentation report (sorted highest fragmentation first)
--------------------------------------------------------------------------------
;WITH frag AS (
    SELECT
        DB_ID()                               AS database_id,
        OBJECT_SCHEMA_NAME(ps.object_id)      AS schema_name,
        OBJECT_NAME(ps.object_id)             AS table_name,
        ps.object_id,
        ps.index_id,
        i.name                                AS index_name,
        ips.index_type_desc,
        ips.avg_fragmentation_in_percent,
        ips.fragment_count,
        ips.page_count,
        ips.avg_fragment_size_in_pages,
        ps.rows /*
        ps.row_count,
        ps.reserved_page_count,
        ps.used_page_count */
    FROM
        sys.dm_db_index_physical_stats(DB_ID(), NULL, NULL, NULL, 'LIMITED') AS ips
        INNER JOIN sys.partitions AS ps
            ON ips.object_id = ps.object_id
            AND ips.index_id = ps.index_id
        LEFT JOIN sys.indexes AS i
            ON ips.object_id = i.object_id
            AND ips.index_id = i.index_id
    WHERE
        ips.database_id = DB_ID()
        AND ps.index_id > 0               -- exclude heaps (index_id = 0)
)
SELECT
    schema_name,
    table_name,
    index_id,
    ISNULL(index_name, '<HEAP>')                  AS index_name,
    index_type_desc,
    avg_fragmentation_in_percent,
    fragment_count,
    page_count,
    avg_fragment_size_in_pages,
    rows /*
    row_count,
    reserved_page_count,
    used_page_count */
FROM
    frag
WHERE
    page_count >= @MinPageCount
ORDER BY
    avg_fragmentation_in_percent DESC,
    fragment_count DESC,
    page_count DESC;

--------------------------------------------------------------------------------
-- Optional: Rebuild or Reorganize indexes based on thresholds
-- NOTE: Uncomment the EXEC block below to apply changes.
-- Always test on non-production first and consider maintenance windows.
--------------------------------------------------------------------------------

/*
SET NOCOUNT ON;

DECLARE @schema_name sysname, @table_name sysname, @index_name sysname;
DECLARE @object_id INT, @index_id INT;
DECLARE @sql NVARCHAR(MAX);
DECLARE @cursor CURSOR;

-- Cursor over indexes that meet the minimum page count
SET @cursor = CURSOR FOR
SELECT schema_name, table_name, object_id, index_id, index_name, avg_fragmentation_in_percent, page_count
FROM frag
WHERE page_count >= @MinPageCount
ORDER BY avg_fragmentation_in_percent DESC;

OPEN @cursor;
FETCH NEXT FROM @cursor INTO @schema_name, @table_name, @object_id, @index_id, @index_name, @avg_fragmentation_in_percent, @page_count;

WHILE @@FETCH_STATUS = 0
BEGIN
    IF @avg_fragmentation_in_percent > @RebuildThreshold
    BEGIN
        -- REBUILD
        SET @sql = N'ALTER INDEX [' + ISNULL(@index_name, '') + N'] ON '
                 + QUOTENAME(@schema_name) + N'.' + QUOTENAME(@table_name)
                 + N' REBUILD WITH (ONLINE = ' + CASE WHEN @OnlineRebuild = 1 THEN N'ON' ELSE N'OFF' END + N');';

        -- If heap (index_name is NULL), can't rebuild: skip
        IF @index_name IS NOT NULL
        BEGIN
            PRINT N'REBUILD: ' + QUOTENAME(@schema_name) + N'.' + QUOTENAME(@table_name) + N' [' + @index_name + N'] (frag=' + CAST(@avg_fragmentation_in_percent AS VARCHAR(10)) + N')';
            EXEC sp_executesql @sql;
        END
    END
    ELSE IF @avg_fragmentation_in_percent >= @ReorgThreshold
    BEGIN
        -- REORGANIZE
        SET @sql = N'ALTER INDEX [' + ISNULL(@index_name, '') + N'] ON '
                 + QUOTENAME(@schema_name) + N'.' + QUOTENAME(@table_name)
                 + N' REORGANIZE;';

        IF @index_name IS NOT NULL
        BEGIN
            PRINT N'REORGANIZE: ' + QUOTENAME(@schema_name) + N'.' + QUOTENAME(@table_name) + N' [' + @index_name + N'] (frag=' + CAST(@avg_fragmentation_in_percent AS VARCHAR(10)) + N')';
            EXEC sp_executesql @sql;
        END
    END
    ELSE
    BEGIN
        PRINT N'SKIP: ' + QUOTENAME(@schema_name) + N'.' + QUOTENAME(@table_name) + N' [' + ISNULL(@index_name,'<HEAP>') + N'] (frag=' + CAST(@avg_fragmentation_in_percent AS VARCHAR(10)) + N')';
    END

    FETCH NEXT FROM @cursor INTO @schema_name, @table_name, @object_id, @index_id, @index_name, @avg_fragmentation_in_percent, @page_count;
END

CLOSE @cursor;
DEALLOCATE @cursor;
SET NOCOUNT OFF;
*/

--------------------------------------------------------------------------------
-- Notes:
-- - sys.dm_db_index_physical_stats(..., LIMITED) is fast but less thorough; use ('DETAILED') for deeper analysis.
-- - Heaps (index_id = 0) are excluded. To include heaps, modify the WHERE filter.
-- - Online rebuild requires appropriate SQL Server edition and may be unavailable for some index types.
-- - Consider maintenance windows and transaction log impact when rebuilding large indexes.
--------------------------------------------------------------------------------
